routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonalInformationController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ExperienceController;
use App\Http\Controllers\EducationController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ProjectInformationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PersonalInformationController::class, 'index'])->name('personal-information.index');
Route::get('/projects', [ProjectController::class, 'index'])->name('projects.index');
Route::get('/experience', [ExperienceController::class, 'index'])->name('experience.index');
Route::get('/education', [EducationController::class, 'index'])->name('education.index');
Route::get('/education', [EducationController::class, 'index'])->name('education.index');
Route::get('/certificates', [CertificateController::class, 'index'])->name('certificates.index');
Route::get('/message', [MessageController::class, 'create'])->name('message.create');
Route::post('/message-store', [MessageController::class, 'store'])->name('message.store');

Route::get('/experience-show-all', [ExperienceController::class, 'showAll'])->name('experience.show.all');
Route::get('/experience-create', [ExperienceController::class, 'create'])->name('experience.create');
Route::post('/experience-store', [ExperienceController::class, 'store'])->name('experience.store');
Route::get('/experience-edit/{experience}', [ExperienceController::class, 'edit'])->name('experience.edit');
Route::patch('/experience-update/{experience}', [ExperienceController::class, 'update'])->name('experience.update');

Route::get('/education-show-all', [EducationController::class, 'showAll'])->name('education.show.all');
Route::get('/education-create', [EducationController::class, 'create'])->name('education.create');
Route::post('/education-store', [EducationController::class, 'store'])->name('education.store');
Route::get('/education-edit/{education}', [EducationController::class, 'edit'])->name('education.edit');
Route::patch('/education-update/{education}', [EducationController::class, 'update'])->name('education.update');

Route::get('/personal-information-show-all', [PersonalInformationController::class, 'showAll'])->name('personal.information.show.all');
Route::get('/personal-information-create', [PersonalInformationController::class, 'create'])->name('personal.information.create');
Route::post('/personal-information-store', [PersonalInformationController::class, 'store'])->name('personal.information.store');
Route::get('/personal-information-edit/{personalInformation}', [PersonalInformationController::class, 'edit'])->name('personal.information.edit');
Route::patch('/personal-information-update/{personalInformation}', [PersonalInformationController::class, 'update'])->name('personal.information.update');

Route::get('/project-show-all', [ProjectController::class, 'showAll'])->name('project.show.all');
Route::get('/project-create', [ProjectController::class, 'create'])->name('project.create');
Route::post('/project-store', [ProjectController::class, 'store'])->name('project.store');
Route::get('/project-edit/{project}', [ProjectController::class, 'edit'])->name('project.edit');
Route::patch('/project-update/{project}', [ProjectController::class, 'update'])->name('project.update');

Route::get('/project-information-show-all/{project}', [ProjectInformationController::class, 'showAll'])->name('project.information.show.all');
Route::get('/project-information-create/{project}', [ProjectInformationController::class, 'create'])->name('project.information.create');
Route::post('/project-information-store/', [ProjectInformationController::class, 'store'])->name('project.information.store');
Route::get('/project-information-edit/{projectInformation}', [ProjectInformationController::class, 'edit'])->name('project.information.edit');
Route::patch('/project-information-update/{projectInformation}', [ProjectInformationController::class, 'update'])->name('project.information.update');

Route::get('/message-index', [MessageController::class, 'index'])->name('message.index');
Route::get('/message-show/{message}', [MessageController::class, 'show'])->name('message.show');

Route::get('/certificate-show-all', [CertificateController::class, 'showAll'])->name('certificate.show.all');
Route::get('/certificate-create', [CertificateController::class, 'create'])->name('certificate.create');
Route::post('/certificate-store', [CertificateController::class, 'store'])->name('certificate.store');
Route::get('/certificate-edit/{certificate}', [CertificateController::class, 'edit'])->name('certificate.edit');
Route::patch('/certificate-update/{certificate}', [CertificateController::class, 'update'])->name('certificate.update');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/View/Components/CvLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class CvLayout extends Component
{
    public function render()
    {
        return view('layouts.cv');
    }
}

resources/views/cv/certificate-index.blade.php
<x-cv-layout>
    <section>
        <header>
            <h2>
                Certificates
            </h2>
        </header>
        <ul class="gallery">

            <li><a href="#"><img src="{{ asset('storage/images/Diploma%20-%20Diploma.jpeg') }}" alt="Diploma SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/PHP%20Fundamentals%20-%20January%202017%20-%20Certificate.jpeg') }}" alt="PHP Fundamentals SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/PHP%20Web%20Development%20-%20October%202016%20-%20Certificate.jpeg') }}" alt="PHP WEB Development SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/JS%20Fundamentals%20-%20May%202018%20-%20Certificate.jpeg') }}" alt="JS Fundamentals SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/JS%20Advanced%20-%20June%202018%20-%20Certificate.jpeg') }}" alt="JS Advanced SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/JS%20Applications%20-%20July%202018%20-%20Certificate.jpeg') }}" alt="JS Application SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/JS%20Frameworks%20with%20AngularJS%20-%20May%202015%20-%20Certificate.jpeg') }}" alt="JS Framework SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/Web%20Fundamentals%20-%20HTML5%20-%20September%202018%20-%20Certificate.jpeg') }}" alt="WEB Fundamentals SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/Drupal%20Site%20Building%20-%20September%202015%20-%20Certificate.jpeg') }}" alt="Drupal Site Building SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/Advanced%20C%23%20-%20February%202016%20-%20Certificate.jpeg') }}" alt="Advanced C# SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/SoftUniada%20-%20January%202016%20-%20Certificate.jpeg') }}" alt="SoftUniada SoftUni"></a></li>
            <li><a href="#"><img src="{{ asset('storage/images/Teamwork%20and%20Personal%20Skills%20-%20Sep%202014%20-%20Certificate.jpeg')}}" alt="Teamwork and Personal Skills"></a></li>

            @foreach($certificates as $certificate)
                <li><a href="#"><img src="{{ asset('storage/images/' . $certificate->image)}}" alt="{{ $certificate->name }}"></a></li>
            @endforeach
        </ul>
    </section>
    <div id="dialog-form" title="Certificates">

    </div>
</x-cv-layout>


<script>
    $(function () {
        dialog = $( "#dialog-form" ).dialog({
            autoOpen: false,
            height: 725,
            width: 725,
            buttons: {
                Cancel: function() {
                    dialog.dialog('close');
                }
            }
        });

        $('.gallery li').on( "click", function() {
            dialog.dialog( "open" );
            $('#dialog-form').empty();
            let imageSrc = $(this).children().children().attr('src');
            $('#dialog-form').append($('<img>').attr('src', imageSrc));
        });
    });
</script>

resources/views/cv/education-index.blade.php
<x-cv-layout>
    <section>
        <header>
            <h2>
                Education
            </h2>
        </header>
        <div class="my-experience">
            @foreach($educations as $education)
                <div>
                    <div>
                        {{ $education->from }}-{{ $education->to }}
                    </div>
                    <div>
                        <p>{{ $education->name }}</p>
                        <p>{{ $education->data }}</p>
                    </div>
                </div>
            @endforeach
        </div>
    </section>
</x-cv-layout>

resources/views/cv/experience-index.blade.php
<x-cv-layout>
    <section>
        <header>
            <h2>
                Experience
            </h2>
        </header>
        <div class="my-experience">
            @foreach($experiences as $experience)
                <div>
                    <div>
                        {{ $experience->from }}-{{ $experience->to }}
                    </div>
                    <div>
                        <p>{{ $experience->name }}</p>
                        <p>{{ $experience->data }}</p>
                    </div>
                </div>
            @endforeach
        </div>
    </section>
</x-cv-layout>

resources/views/cv/message-create.blade.php
<x-cv-layout>
    <section>
        <header>
            <h2>
                Contact
            </h2>
        </header>
        <div class="send-message">
            <form action="{{ route('message.store') }}" method="post">
                @csrf

                <fieldset>
                    <legend>DROP ME A LINE</legend>
                    <p class="field">
                        <span class="input">
                            <input type="text" name="name" value="{{ old('name') }}" placeholder="Your Name">
                            <span class="actions"></span>
                            <i class="fas fa-user"></i>
                        </span>
                    </p>
                    @if($errors->get('name'))
                        <ul class="errors">
                            @foreach ($errors->get('name') as $message)
                                <li>{{ $message }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <p class="field">
                        <span class="input">
                            <input type="text" name="email" value="{{ old('email') }}"  placeholder="Your Email">
                            <span class="actions"></span>
                            <i class="fas fa-envelope"></i>
                        </span>
                    </p>
                    @if($errors->get('email'))
                        <ul class="errors">
                            @foreach ($errors->get('email') as $message)
                                <li>{{ $message }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <p class="field">
                        <span class="input">
                            <textarea name="message" cols="30" rows="10" placeholder="Your Message...">{{ old('message') }}</textarea>
                            <span class="actions"></span>
                        </span>
                    </p>
                    @if($errors->get('message'))
                        <ul class="errors">
                            @foreach ($errors->get('message') as $message)
                                <li>{{ $message }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <input type="submit" value="SAY HELLO!">
                </fieldset>
            </form>
        </div>
    </section>
</x-cv-layout>

resources/views/cv/personal-information-index.blade.php
<x-cv-layout>
    <section>
        <header>
            <h2>
                Home
            </h2>
        </header>
        <div class="my-information">
            @foreach($personalInformation as $row)
                <div>
                    <span>{{ $row->key }}:</span> {{ $row->value }}
                </div>
            @endforeach
        </div>
        @if($personalInformationRow)
            <div class="personal-information">
                <h4>{{ $personalInformationRow->key }}</h4>
                <p>
                    {{ $personalInformationRow->value }}
                </p>
            </div>
        @endif
    </section>
</x-cv-layout>

resources/views/cv/project-index.blade.php
<x-cv-layout>
    <section>
        <header>
            <h2>
                Projects
            </h2>
        </header>
        <div class="project-information">
            @foreach($projects as $project)
                <div>
                    @foreach($project->projectInformation as $row)
                        @if ($row->link)
                            <div><span>{{ $row->key }}: </span> <a target="_blank" href="{{ $row->link }}">{{ $row->value }}</a></div>
                        @else
                            <div><span>{{ $row->key }}: </span>{{ $row->value }}</div>
                        @endif
                    @endforeach
                </div>
            @endforeach
        </div>
    </section>
</x-cv-layout>